// assets/js/component/react/BasicNavbar.jsx
import React, { Component } from "react";
import {Form, Col, Button, FormGroup, FormControl, Checkbox, Nav, NavItem, Navbar} from 'react-bootstrap'

class BasicNavBar extends Component {
    constructor() {
        super();
    }

    render() {
        return (
            <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <button className="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#bs-example-navbar-collapse-1">
            <span className="navbar-toggler-icon"></span>
    </button>
    <a className="navbar-brand" href="#">Brand</a>
        <div className="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul className="navbar-nav">
                <li className="nav-item active">
                    <a className="nav-link" href="#">Link <span
                        className="sr-only">(current)</span></a>
                </li>
                <li className="nav-item">
                    <a className="nav-link" href="#">Link</a>
                </li>
                <li className="nav-item dropdown">
                    <a className="nav-link dropdown-toggle" href="http://example.com"
                       id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
                    <div className="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a className="dropdown-item" href="#">Action</a> <a
                        className="dropdown-item" href="#">Another action</a> <a
                        className="dropdown-item" href="#">Something else here</a>
                        <div className="dropdown-divider">
                        </div>
                        <a className="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
            <form className="form-inline">
                <input className="form-control mr-sm-2" type="text"/>
                <button className="btn btn-primary my-2 my-sm-0" type="submit">
                    Search
                </button>
            </form>
            <ul className="navbar-nav ml-md-auto">
                <li className="nav-item active">
                    <a className="nav-link" href="#">Link <span
                        className="sr-only">(current)</span></a>
                </li>
                <li className="nav-item dropdown">
                    <a className="nav-link dropdown-toggle" href="http://example.com"
                       id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
                    <div className="dropdown-menu dropdown-menu-right"
                         aria-labelledby="navbarDropdownMenuLink">
                        <a className="dropdown-item" href="#">Action</a> <a
                        className="dropdown-item" href="#">Another action</a> <a
                        className="dropdown-item" href="#">Something else here</a>
                        <div className="dropdown-divider">
                        </div>
                        <a className="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
        </div>
        </nav>
        );
    }
}


export default BasicNavBar;

// assets/js/component/vue/BasicNavBar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Link <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com"
                       id="navbarDropdownMenuLink1" data-toggle="dropdown">Dropdown link</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a> <a
                            class="dropdown-item" href="#">Another action</a> <a
                            class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider">
                        </div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline">
                <input class="form-control mr-sm-2" type="text"/>
                <button class="btn btn-primary my-2 my-sm-0" type="submit">
                    Search
                </button>
            </form>
            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Link <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com"
                       id="navbarDropdownMenuLink2" data-toggle="dropdown">Dropdown link</a>
                    <div class="dropdown-menu dropdown-menu-right"
                         aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a> <a
                            class="dropdown-item" href="#">Another action</a> <a
                            class="dropdown-item" href="#">Something else here</a>
                        <div class="dropdown-divider">
                        </div>
                        <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</template>
<script>
    export default {};
</script>
